# Generated by Django 5.1.1 on 2024-10-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_student_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('when', models.CharField(max_length=100)),
                ('where', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
