# Generated by Django 5.1.1 on 2024-10-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_attendance_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
