# Generated by Django 5.1.1 on 2024-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0009_attendance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.CharField(default='device1', max_length=200),
            preserve_default=False,
        ),
    ]
