# Generated by Django 5.1.1 on 2024-10-08 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0011_alter_event_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.device'),
        ),
    ]
