# Generated by Django 5.1.1 on 2024-10-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0013_securitytoken_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.securitytoken'),
            preserve_default=False,
        ),
    ]
