# Generated by Django 5.1.1 on 2024-10-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0014_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitytoken',
            name='token',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
