# Generated by Django 5.1.1 on 2024-10-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
